### ISSUE TITLE
可以？

### ISSUE THREAD

**Issue by cjj1472111531** [taishan1994/pytorch_bert_relation_extraction#1]
能说一说所需要的环境？

**Comment by taishan1994** [comment]
> 能说一说所需要的环境？

pytorch>=1.6+
transformers>=4.x+
具体的忘记是什么版本的了

**Comment by cjj1472111531** [comment]
models这里就是出错了，在19行这里是跑不通的

**Comment by taishan1994** [comment]
> models这里就是出错了，在19行这里是跑不通的

具体那个文件，报了什么错，贴个图吧。
