### ISSUE TITLE
main.py的236行trainer = Trainer(args, None, None, None)

### ISSUE THREAD

**Issue by GiveMeAnApple99** [taishan1994/pytorch_bert_relation_extraction#3]
main.py的236行trainer = Trainer(args, None, None, None)，怎么写的是None？这样根本没有把train_loader,dev_loader,test_loader传过去呀

**Comment by taishan1994** [comment]
> main.py的236行trainer = Trainer(args, None, None, None)，怎么写的是None？这样根本没有把train_loader,dev_loader,test_loader传过去呀

因为下面的一段代码是预测的，不需要上述的，要训练的话是注释掉的那些代码。
