### ISSUE TITLE
希望大佬帮看一下

### ISSUE THREAD

**Issue by AIwjy94** [taishan1994/pytorch_bert_relation_extraction#4]
Traceback (most recent call last):
  File "main.py", line 249, in <module>
    result = trainer.predict(tokenizer, text, id2label, args, ids)
  File "main.py", line 147, in predict
    model, optimizer, epoch, loss = self.load_ckp(model, optimizer, checkpoint)
  File "main.py", line 37, in load_ckp
    checkpoint = torch.load(checkpoint_path)
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by taishan1994** [comment]
> Traceback (most recent call last): File "main.py", line 249, in result = trainer.predict(tokenizer, text, id2label, args, ids) File "main.py", line 147, in predict model, optimizer, epoch, loss = self.load_ckp(model, optimizer, checkpoint) File "main.py", line 37, in load_ckp checkpoint = torch.load(checkpoint_path) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 594, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load result = unpickler.load() File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 845, in persistent_load load_tensor(data_type, size, key, _maybe_decode_ascii(location)) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 834, in load_tensor loaded_storages[key] = restore_location(storage, location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 175, in default_restore_location result = fn(storage, location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 151, in _cuda_deserialize device = validate_cuda_device(location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

你机器上没有GPU，要将模型和数据都转到cpu上。

**Comment by AIwjy94** [comment]
> 
这是我在预测的时候出现的

> 

我刚开始偷懒，想直接用大佬的模型弄预测，出现错误，我自己训练了模型，跑出来就对了

**Comment by AIwjy94** [comment]
> > Traceback (most recent call last): File "main.py", line 249, in result = trainer.predict(tokenizer, text, id2label, args, ids) File "main.py", line 147, in predict model, optimizer, epoch, loss = self.load_ckp(model, optimizer, checkpoint) File "main.py", line 37, in load_ckp checkpoint = torch.load(checkpoint_path) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 594, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load result = unpickler.load() File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 845, in persistent_load load_tensor(data_type, size, key, _maybe_decode_ascii(location)) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 834, in load_tensor loaded_storages[key] = restore_location(storage, location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 175, in default_restore_location result = fn(storage, location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 151, in _cuda_deserialize device = validate_cuda_device(location) File "/Users/wjy/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
> 
> 你机器上没有GPU，要将模型和数据都转到cpu上。

我刚开始偷懒，想直接用大佬的模型弄预测，出现错误，我自己训练了模型，跑出来就对了
