### ISSUE TITLE
        self.linear = nn.Linear(out_dims * 4, args.num_tags)

### ISSUE THREAD

**Issue by AIwjy94** [taishan1994/pytorch_bert_relation_extraction#5]
self.linear = nn.Linear(out_dims * 4, args.num_tags)
你好，大佬，我想问下这里为什么*4

**Comment by taishan1994** [comment]
> ```
>     self.linear = nn.Linear(out_dims * 4, args.num_tags)
> ```
> 
> 你好，大佬，我想问下这里为什么*4


取了object首尾和subject的首尾，共4*out_dims
